{% set name = "symbol_count" %}
{% set version = "1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
    noarch: python

source: 
  path: ../src

requirements:
  host:
    - python
  run:
    - python

about:
  home: https://github.com/bidauxpoto/symbol_count
  summary: no
